[package]
name = "widget"
version = "1.0.2"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = "0.8.0"
schemars = "0.8.12"
serde = "1.0.160"
serde_json = "1.0.96"
chrono = { version = "0.4.24", default-features = false, features = ["alloc"] }
chrono-tz = "0.8.2"
