name: Build release

on:
  push:
    tags:
      # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install wasm-tools
      run: cargo install --git https://github.com/bytecodealliance/wasm-tools wasm-tools
    - name: Validate WIT
      run: wasm-tools component wit wg_display_widget_wit/wit
    - name: Add WASM target
      run: rustup target add wasm32-wasip2
    - name: Build
      working-directory: ./widget
      run: cargo build --target wasm32-wasip2 --release
    - uses: ncipollo/release-action@v1
      with:
          artifacts: "widget/target/wasm32-wasip2/release/widget.wasm"
          artifactErrorsFailBuild: true
